version: "3.8"

services:
  app:
    container_name: strategy-frontend
    image: strategy-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 3000:3000

